{{- if .Values.extraEnv -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stroem-worker.fullname" . }}-env
  labels:
    {{- include "stroem-worker.labels" . | nindent 4 }}
data:
  {{- range $name, $config := .Values.extraEnv }}
  {{ $name }}: {{ $config | quote }}
  {{- end }}
{{- end }}