apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stroem-worker.fullname" . }}
  labels:
    {{- include "stroem-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stroem-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        checksum/secrets-env: {{ include (print $.Template.BasePath "/secrets-env.yaml") . | sha256sum }}
        checksum/secrets-env-ref: {{ .Values.envFromSecret | default "" | sha256sum }}
      {{ if .Values.podAnnotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stroem-worker.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stroem-worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $key, $value := .Values.args }}
            - "--{{ $key }}"
            - {{ $value | quote }}
            {{- end }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          {{- if .Values.extraEnv }}
          - configMapRef:
              name: {{ include "stroem-worker.fullname" . }}-env
          {{- end }}
          {{- if .Values.extraSecretEnv }}
          - secretRef:
              name: {{ include "stroem-worker.fullname" . }}-env
          {{- end }}
          {{- if .Values.envFromSecret }}
          - secretRef:
              name: {{ .Values.envFromSecret }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- tpl (toYaml .) $ | nindent 12 -}}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- tpl (toYaml .) $ | nindent 8 -}}
      {{- end }}