{{- if .Values.extraSecretEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stroem-worker.fullname" . }}-env
  labels:
    {{- include "stroem-worker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $config := .Values.extraSecretEnv }}
  {{ $name }}: {{ $config | b64enc | quote  }}
  {{- end }}
{{- end }}