{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stroem-server.fullname" . }}-config
  labels:
    {{- include "stroem-server.labels" . | nindent 4 }}
data:
  stroem.yaml: "{{ toYaml .Values.config | indent 2 }}"
{{- end }}