{{- if .Values.persistentVolumeClaim.enabled }}
{{- if not .Values.persistentVolumeClaim.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stroem-server.fullname" . }}
  labels:
    {{- include "stroem-server.labels" . | nindent 4 }}
  {{- with .Values.persistentVolumeClaim.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- range .Values.persistentVolumeClaim.accessModes}}
  accessModes:
    - {{ . }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  {{- with .Values.persistentVolumeClaim.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
  {{- with .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.persistentVolumeClaim.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
